import React,{useState} from 'react';
import {View,Text,Image,Alert,KeyboardAvoidingView,Platform} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,updateProfile,sendPasswordResetEmail} from 'firebase/auth';
import {getAuthInstance} from '../firebase';import {useAuth} from '../AuthContext';import {Screen,Field,Button,Muted} from '../ui';import {C} from '../theme';
const ERR={'auth/invalid-email':'E-mail inválido.','auth/missing-password':'Digite a senha.','auth/weak-password':'A senha precisa ter pelo menos 6 caracteres.','auth/email-already-in-use':'Este e-mail já tem conta. Entre com a senha.','auth/invalid-credential':'E-mail ou senha incorretos.','auth/user-not-found':'E-mail ou senha incorretos.','auth/wrong-password':'E-mail ou senha incorretos.','auth/network-request-failed':'Sem internet. Tente de novo.','auth/operation-not-allowed':'Ative o login por e-mail/senha no Firebase Authentication.','auth/too-many-requests':'Muitas tentativas. Aguarde um pouco.'};
export default function AuthScreen(){const[mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[busy,setBusy]=useState(false);
const submit=async()=>{setBusy(true);try{const auth=getAuthInstance();if(mode==='signup'){if(name.trim().length<2)throw{code:'x',message:'Digite seu nome.'};const cred=await createUserWithEmailAndPassword(auth,email.trim(),pass);await updateProfile(cred.user,{displayName:name.trim()});setUser(cred.user)}else{const cred=await signInWithEmailAndPassword(auth,email.trim(),pass);setUser(cred.user)}}catch(e){Alert.alert(mode==='signup'?'Não foi possível criar a conta':'Não foi possível entrar',ERR[e.code]||e.message||'Tente novamente.')}finally{setBusy(false)}};
const reset=async()=>{if(!email.trim())return Alert.alert('Recuperar senha','Digite seu e-mail no campo acima.');try{await sendPasswordResetEmail(getAuthInstance(),email.trim());Alert.alert('E-mail enviado','Confira sua caixa de entrada para criar uma nova senha.')}catch(e){Alert.alert('Recuperar senha',ERR[e.code]||e.message||'Tente novamente.')}};
return <Screen edges={[]} pad={false}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined}><LinearGradient colors={[C.pine,C.deep]} style={{paddingTop:84,paddingBottom:40,paddingHorizontal:24,borderBottomLeftRadius:32,borderBottomRightRadius:32}}><Image source={require('../../assets/icon.png')} style={{width:64,height:64,borderRadius:16,marginBottom:18}}/><Text style={{color:'#fff',fontSize:32,fontWeight:'800'}}>Man Checkout</Text><Text style={{color:'#CDEFE3',fontSize:15,marginTop:6}}>Receba por PIX, cripto e links de pagamento com a sua marca.</Text></LinearGradient><View style={{padding:24}}><Text style={{fontSize:20,fontWeight:'800',color:C.ink,marginBottom:16}}>{mode==='login'?'Entrar na conta':'Criar conta'}</Text>{mode==='signup'&&<Field label="Nome" value={name} onChangeText={setName} autoCapitalize="words" placeholder="Seu nome ou da loja"/>}<Field label="E-mail" value={email} onChangeText={setEmail} keyboardType="email-address" placeholder="voce@exemplo.com"/><Field label="Senha" value={pass} onChangeText={setPass} secureTextEntry placeholder="Mínimo 6 caracteres"/><Button title={mode==='login'?'Entrar':'Criar conta'} onPress={submit} loading={busy}/>{mode==='login'&&<Button kind="ghost" title="Esqueci a senha" onPress={reset} style={{marginTop:10}}/>}<View style={{marginTop:18,alignItems:'center'}}><Muted>{mode==='login'?'Ainda não tem conta? ':'Já tem conta? '}<Text style={{color:C.pine,fontWeight:'800'}} onPress={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Criar agora':'Entrar'}</Text></Muted></View></View></KeyboardAvoidingView></Screen>}