import React from 'react';
import {View,Text,TextInput,TouchableOpacity,ActivityIndicator,ScrollView,StyleSheet,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {C,STATUS} from './theme';
export function Screen({children,scroll=true,pad=true,edges=['top']}){const Body=scroll?ScrollView:View;return <SafeAreaView style={{flex:1,backgroundColor:C.bg}} edges={edges}><Body style={{flex:1}} contentContainerStyle={scroll?{padding:pad?20:0,paddingBottom:48}:undefined} keyboardShouldPersistTaps="handled">{scroll?children:<View style={{flex:1,padding:pad?20:0}}>{children}</View>}</Body></SafeAreaView>}
export const H1=({children,style})=><Text style={[s.h1,style]}>{children}</Text>;
export const H2=({children,style})=><Text style={[s.h2,style]}>{children}</Text>;
export const Muted=({children,style})=><Text style={[s.muted,style]}>{children}</Text>;
export function Card({children,style}){return <View style={[s.card,style]}>{children}</View>}
export function Field({label,hint,multiline,style,...props}){return <View style={{marginBottom:14}}>{label?<Text style={s.label}>{label}</Text>:null}<TextInput placeholderTextColor="#8FA3A2" multiline={multiline} style={[s.input,multiline&&{height:92,textAlignVertical:'top'},style]} autoCapitalize="none" {...props}/>{hint?<Text style={s.hint}>{hint}</Text>:null}</View>}
export function Button({title,onPress,loading,kind='primary',disabled,style}){const isP=kind==='primary',isD=kind==='danger';return <TouchableOpacity activeOpacity={.85} onPress={onPress} disabled={loading||disabled} style={[s.btn,isP&&{backgroundColor:C.pine},kind==='ghost'&&{backgroundColor:'transparent',borderWidth:1.5,borderColor:C.line},isD&&{backgroundColor:C.badSoft},(loading||disabled)&&{opacity:.55},style]}>{loading?<ActivityIndicator color={isP?'#fff':C.pine}/>:<Text style={[s.btnTxt,!isP&&{color:isD?C.bad:C.ink}]}>{title}</Text>}</TouchableOpacity>}
export function Chips({options,value,onChange}){return <View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:14}}>{options.map(o=>{const on=o.value===value;return <TouchableOpacity key={o.value} onPress={()=>onChange(o.value)} style={[s.chip,on&&{backgroundColor:C.deep,borderColor:C.deep}]}><Text style={[s.chipTxt,on&&{color:'#fff'}]}>{o.label}</Text></TouchableOpacity>})}</View>}
export function Badge({status}){const st=STATUS[status]||STATUS.PENDING;return <View style={{backgroundColor:st.bg,paddingHorizontal:10,paddingVertical:4,borderRadius:99}}><Text style={{color:st.fg,fontWeight:'700',fontSize:12}}>{st.label}</Text></View>}
export function Empty({title,text}){return <View style={{alignItems:'center',paddingVertical:36,paddingHorizontal:12}}><Text style={{fontSize:16,fontWeight:'700',color:C.ink,marginBottom:6}}>{title}</Text><Text style={[s.muted,{textAlign:'center'}]}>{text}</Text></View>}
export const mono=Platform.select({ios:'Menlo',default:'monospace'});
const s=StyleSheet.create({h1:{fontSize:28,fontWeight:'800',color:C.ink,letterSpacing:-.5},h2:{fontSize:18,fontWeight:'700',color:C.ink,marginBottom:10},muted:{color:C.mute,fontSize:14,lineHeight:20},card:{backgroundColor:C.card,borderRadius:16,padding:16,marginBottom:14,borderWidth:1,borderColor:C.line},label:{fontSize:13,fontWeight:'700',color:C.ink,marginBottom:6},hint:{fontSize:12,color:C.mute,marginTop:5,lineHeight:17},input:{backgroundColor:'#fff',borderWidth:1.5,borderColor:C.line,borderRadius:12,paddingHorizontal:14,paddingVertical:12,fontSize:16,color:C.ink},btn:{borderRadius:14,paddingVertical:15,alignItems:'center',justifyContent:'center',marginTop:4},btnTxt:{color:'#fff',fontSize:16,fontWeight:'700'},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:99,borderWidth:1.5,borderColor:C.line,backgroundColor:'#fff'},chipTxt:{color:C.ink,fontWeight:'600',fontSize:14}});
